### PR TITLE
[WIP] Update OpenMM tutorials

### PR DESCRIPTION
**Pull request by jchodera**
This PR will
- [x] update OpenMM tutorials using the current content of https://github.com/choderalab/openmm7tutorials
- [ ] push from the `preview` branch to a [special preview site](http://openmm-org-preview.s3-website-us-east-1.amazonaws.com/), while `master` branch will push to the [main `openmm.org` site](http://openmm.org)

Still a work in progress.

cc: https://github.com/pandegroup/openmm/issues/1868

### CODE REVIEW

**Comment by mpharrigan** [comment]
Let me know if/when you want to merge this, or you can submit a PR directly to the openmm-org repo to supersede my open one there.

**Comment by jchodera** [comment]
> Let me know if/when you want to merge this, or you can submit a PR directly to the openmm-org repo to supersede my open one there.

Thanks! Maybe I can just close this and open the PR directly to openmm-org.

I don't have write access to the `openmm-org` repo, though, which will make it impossible for me to set up a `preview` branch there that will push to my preview page.

**Comment by jchodera** [comment]
This is ready for @lnaden @rafwiewiora @chayast to review and correct:
http://openmm-org-preview.s3-website-us-east-1.amazonaws.com/tutorials/index.html

**Comment by jchodera** [comment]
Closing this to open a PR directly into https://github.com/pandegroup/openmm-org

**Pull request closed without merging**
